class API_URL:
    BINANCEAPI_BASE = 'https://api.binance.com'
    BINANCEAPI_TICKER24 = '/api/v1/ticker/24hr'
    BINANCEAPI_CANDLESTICK = '/api/v1/klines'
    BINANCEAPI_TICKER_PRICE = '/api/v3/ticker/price'
    BINANCEAPI_ACCOUNT = '/api/v3/account'
    BINANCEAPI_EXCHANGE_INFO = '/api/v1/exchangeInfo'
    BINANCEAPI_ORDER = '/api/v3/order'
    BINANCEAPI_OPEN_ORDERS = '/api/v3/openOrders'
    BINANCEAPI_ALL_ORDERS = '/api/v3/allOrders'
    BINANCE_KEY = 'x3wD38hF7Sr1o3f6AnF8BVdEQWp9a0UjJ4oLRVJu2F91NNKpJXGg6xazd4pW7D6b'
    BINANCE_SECRET = 'jmiTomJmIL5O1Wov32k6ZZM7DL1IoU0uBJhoTkjDKzzcOoS0cKsl6QCGEyCBt32M'